[package]
name = "unicode-bidi"
version = "0.1.0"
authors = ["The Servo Project Developers"]
license = "MIT / Apache-2.0"
description = "Implementation of the Unicode Bidirectional Algorithm"

[lib]
name = "unicode_bidi"

[dependencies]
matches = "0.1"
bitflags = "0.2"
